version: "3.9"

networks:
  lan:
    name: ${container_name}_lan
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ${bridge_name}
    external: false
    ipam:
      config: 
        - subnet: "${ipv4_subnet}"
          gateway: "${ipv4_gateway}"

services:
  git_server:
    image: ${image_name}
    container_name: ${container_name}
    build:
      context: .
      dockerfile: DOCKERFILE
      args:
        comma_seperated_host_list: ${https_hosts}
          # used when generating SSL certificate for HTTPS
        user_id: ${uid}
        group_id: ${gid}
          # also used for generating SSL certificates. Controls the
          # permissions on the certificate and key files. Make sure it
          # matches the USER_UID and USER_GID values in the 
          # 'environment' section.
    restart: always
    networks:
      lan:
        ipv4_address: "${ipv4_address}"
    ports:
      - "80"
      - "443"
    volumes:
      - ./_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Note that after the container is built for the first time, Gitea 
      # doesn't refer to these variables for the configuration. 
      #
      # ------------------------
      # --- GENERAL SETTINGS ---
      # ------------------------
      - USER=git
          # the username of the user than runs Gitea within the container.
      - USER_UID=${uid}
      - USER_GID=${gid}
          # the user ID and group ID must match the ownership of the ./_data 
          # directory.
      # --------------------
      # --- WEB SETTINGS ---
      # --------------------
      - GITEA__server__HTTP_PORT=80
     # - GITEA__server__HTTP_PORT=443
          # Gitea can only listen on one port at a time. By default, this is
          # 3000. If we were only using HTTP, we'd traditionally set it to 80
          # in this config or (more commonly) keep it at 3000 and map it to 
          # 80 via the 'ports' section in this docker-compose file.
          #
          # Anyways. We're using HTTPS, and we're exposing it directly in the
          # 'ports' section below without any mapping, so we use 443.
      - GITEA__server__HTTP_ADDR=${ipv4_address}
      - GITEA__server__ROOT_URL=http://${ipv4_address}:80/
     # - GITEA__server__ROOT_URL=https://10.65.196.42:443/
          # Change this to https://repos.all.home.arpa:443/ once we get DNS 
          # working.
      # -----------------
      # --- FOR HTTPS ---
      # -----------------
     # - GITEA__server__PROTOCOL=https
     # - GITEA__server__CERT_FILE=/ssl/cert.pem
     # - GITEA__server__KEY_FILE=/ssl/key.pem
          # we made the /ssl folder in the DOCKERFILE
     # - GITEA__server__REDIRECT_OTHER_PORT=true
     # - GITEA__server__PORT_TO_REDIRECT=80
